### ISSUE TITLE
Suggestion: Add datetime to export filename and allow tags

### ISSUE THREAD

**Issue by atthepub** [firebug/netexport#13]
Nice to have - exported files have the option to append a date/time stamp in a sortable fashion (e.g., YYYYMMDDHHMMSSmm) before the .har extension.   It would also be great to allow the user to add a tag of sorts to identify the action taken when the export was made (e.g., logon, selectingXYZ, updatingABC, etc)

**Comment by janodvarko** [comment]
Yes it is now possible to provide a custom file name.

There is a new pref: extensions.firebug.netexport.defaultFileName
You can set it to a string that is used as a format string for generating the name
An example: myname-%Y-%m-%d-endofthename

Read more about the format:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleFormat

NetExport is currently bundled in Firebug.next, this new feature available in alpha 10
https://github.com/firebug/firebug.next/releases/tag/firebug-3.0.0-alpha.10

Honza
