### ISSUE TITLE
NetExport autoExport doest not work

### ISSUE THREAD

**Issue by selenUser** [firebug/netexport#19]
working with Selenium, but also tried this manually, when open FF browser with autoexport = true and trying to run window.NetExport.triggerExport("tokenName") getting undefined netExport.
When turn off autoExport manually and then turning on, same action working well

**Comment by JosephCastro** [comment]
I trying the same but programmatically (like manually), but doesn't work :(

**Comment by janodvarko** [comment]
Here is the thread you need to follow
https://groups.google.com/d/msg/firebug/oJwLFniRs-E/-uLDdW2CZ5YJ

Honza
