### ISSUE TITLE
Addon needs to be signed

### ISSUE THREAD

**Issue by gusowski1** [firebug/netexport#20]
https://wiki.mozilla.org/Addons/Extension_Signing
Firefox 40: Firefox warns about signatures but doesn't enforce them.
Firefox 41: Firefox will have a preference that allows signature enforcement to be disabled (xpinstall.signatures.required in about:config).
Firefox 42: Release and Beta versions of Firefox will not allow unsigned extensions to be installed, with no override.

**Comment by janodvarko** [comment]
Manual HAR Export is natively supported by Firefox 42+. To trigger HAR export automatically from within the page you need HAR Export Trigger extension.
https://github.com/firebug/har-export-trigger/

The above configuration is recommended and replaces NetExport extension.

Honza
