### ISSUE TITLE
Installed netExport-0.9b7.xpi, but not seeing Export option

### ISSUE THREAD

**Issue by dianev** [firebug/netexport#22]
I installed netExport-0.9b7.xpi, recycled firefox, and when I click on the firebug icon, I expect to see a new "export" option under the "Net" tab, but it is not there.  Any help you can provide would be appreciated.  I am running FF 45.3.0.

**Comment by janodvarko** [comment]
NetExport extension has been replaced by HarExportTrigger see more:
http://www.softwareishard.com/blog/har-export-trigger/

Honza
